### ISSUE TITLE
Server suddenly crashes when client registration

### ISSUE THREAD

**Issue by benjamin658** [moleike/node-lwm2m#2]
Hi, I'm trying to build a lwm2m server with this module, here is my server's sample code:

```
const server = require('lwm2m').createServer();

server.on('register', function(params, accept) {
  setImmediate(function() {
    server
    .read(params.ep, '3/0/9')
    .then(function(device) {
      console.log(JSON.stringify(device, null, 4));
    })
  });
  accept();
});

server.listen(5683);
```

And I use [this tool](https://github.com/OpenMobileAlliance/OMA-LWM2M-DevKit) to test the server. When I register a client, the server suddenly crashes with the error:

```
/Users/benHu/Workspace/Lab/lwm2m-server/node_modules/coap/lib/option_converter.js:143
    throw new Error('No matching format found')
    ^

Error: No matching format found
    at contentFormatToString (/Users/benHu/Workspace/Lab/lwm2m-server/node_modules/coap/lib/option_converter.js:143:11)
    at module.exports.fromBinary (/Users/benHu/Workspace/Lab/lwm2m-server/node_modules/coap/lib/option_converter.js:32:10)
    at packetToMessage (/Users/benHu/Workspace/Lab/lwm2m-server/node_modules/coap/lib/helpers.js:113:20)
    at new IncomingMessage (/Users/benHu/Workspace/Lab/lwm2m-server/node_modules/coap/lib/incoming_message.js:16:3)
    at Agent.handle [as _handle] (/Users/benHu/Workspace/Lab/lwm2m-server/node_modules/coap/lib/agent.js:267:16)
    at Socket.<anonymous> (/Users/benHu/Workspace/Lab/lwm2m-server/node_modules/coap/lib/agent.js:85:10)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at UDP.onMessage [as onmessage] (dgram.js:619:8)
```

I also trying to figure out the error caused by node_coap, in the test case I saw this:

```
  describe('with the \'Content-Format\' header and a wrong value in the request', function() {
    it('should return a 5.00 error to the cliend', function(done) {
      send(generate({
        options: [{
          name: 'Content-Format'
          , value: new Buffer([1541])
        }]
      }))

      client.on('message', function(msg) {
        var response = parse(msg);

        expect(response.code).to.equal('5.00')
        expect(response.payload.toString()).to.equal('No matching format found')

        done()
      })

      server.on('request', function(req) {
        assert(false, 'This should not happen')
      })
    })
  })
```

**Comment by moleike** [comment]
Hi,
These are the content formats (text and binary) that are registered with node-coap:
```js
var text = 'text/plain';
var link = 'application/link-format';
var opaque = 'application/octet-stream';
var tlv = 'application/vnd.oma.lwm2m+tlv';
var json = 'application/vnd.oma.lwm2m+json';
var formats = [
  { name: text, value : 0 }, 
  { name: link, value : 40 },
  { name: opaque, value : 42 },
  { name: tlv, value : 11542 },
  { name: json, value : 11543 },
];
```

But OMA LWM2M Devkit defines [1]:

```js
Lwm2mDevKit.Copper.__defineGetter__("CONTENT_TYPE_APPLICATION_VND_OMA_LWM2M_TEXT", function() { return 1541; });
```
And also:
```js
Lwm2mDevKit.Copper.__defineGetter__("CONTENT_TYPE_TEXT_PLAIN", function() { return 0; });
```
The former is actually not registered (https://www.iana.org/assignments/media-types/media-types.xhtml) and is not defined in the current LwM2M spec.

So I am guessing you are sending a response from the client with an invalid text content format.
Try to see if that is the case.

1: https://github.com/OpenMobileAlliance/OMA-LWM2M-DevKit/blob/0146b3fc2dedf8d8bf4e6fd0ba7cc780222d4885/chrome/content/copper/CoapRFC7252.js#L174

**Comment by moleike** [comment]
https://github.com/OpenMobileAlliance/OMA-LWM2M-DevKit/pull/11

**Comment by benjamin658** [comment]
Thanks for your help!

BTW, before the DevKit merge the PR, do you have any recommend tool to test the lwm2m server?

**Comment by moleike** [comment]
I routinely use [wakaama](https://github.com/eclipse/wakaama) client library, it comes with a test client that is easy to use.

**Comment by benjamin658** [comment]
Thanks a lot! I think the issue can be closed now.
